name: New Club/Team Setup Request
description: Request to add a new rowing club's safety matrix to the system.
title: "[NEW] <Club Name Here>"
labels: new club

body:
  - type: markdown
    attributes:
      value: |
        # Thanks for your interest in using the River Status Dashboard!
        
        Filling out this form means you are ready to start using the app for your club and requires a completed Safety Matrix Template (which you can get from the [project website](https://openrowing.com/projects/riverstatus)).
        
        Once you submit the template, you will have your own dedicated space to **publicly** discuss the addition of your club with the developers (who may have additional questions or may discover errors with your safety matrix). 

  - type: textarea
    attributes:
      label: Share your completed safety matrix template
      description: |
        Need a copy of the template? You can get it from [our website](https://openrowing.com/projects/riverstatus).

        You may modify the template as much as you like (i.e. to add or remove zones, specify your own additional information, etc). Please make sure you specify what data sources you are using for each of the metrics you want to use.

        To submit your matrix, please paste a (publicly accessible) link here or upload it as a file. 

        Tip: You can attach files by clicking this area to highlight it and then dragging or pasting files in.
    validations:
      required: true
      
  - type: textarea
    id: additional-notes
    attributes:
      label: Any additional notes or context?
      description: Is there anything else you'd like us to know about your club's safety policies or specific requirements?
      placeholder: Additional comments...
    validations:
      required: false